### ISSUE TITLE
New Tab Button Crashes the App, Download Progress stuck at 0% and Many More......

### ISSUE THREAD

**Issue by ggtech360** [SHAYKHUL/Pysurf#7]
So upon testing, I noticed these bug.

- When clicking the New Tab button, it crashes the app.
- Bookmarks and History Doesn't Work. Download Option Doesn't show Downloaded files.
- Files Download but Progress is stuck at 0%. Canceling causes Crash.

**System Used for Testing**: `Arch Linux`

**Comment by SHAYKHUL** [comment]
I'm   apologize for this issue . The issues you’ve encountered are due to certain features not being properly implemented. I’m actively working on resolving them and ensuring the app functions as expected.  

Thank you for your efforts in testing and reporting these bugs—it’s invaluable in improving the app. I’ll keep you updated on the progress and share a fix as soon as it’s ready.  

Your patience and support mean a lot!

**Comment by SHAYKHUL** [comment]
This issues is solved. please check our latest version
